name: Create PR

on:
  workflow_dispatch:
  
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Create repository dispatch event
      uses: actions/github-script@main
      with:
        script: |
          return await github.rest.pulls.create({
            owner: 'im-github-training',
            repo: 'pr-test',
            base: 'my-first-branch',
            head: 'main',
            title: 'Test',
            body: 'Test'
          });
            
