name: Create Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create issue
      uses: actions/github-script@v7
      with:
        script: |
          return await github.rest.issues.create({
            owner: 'im-github-training',
            repo: 'im-github-training.github.io',
            title: 'Issue title',
            body: 'Issue body'
          });
