name: Create PR

on:
  workflow_dispatch:
  
permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # or a repo scoped Personal Access Token (PAT) for more permissions
        base: "main" # The base branch in the parent repository
        push-to-fork: "im-github-training/pr-test" # Specify the fork repository
        title: "Your Pull Request Title"
        body: "The body of your pull request."


            
