name: Create Issue

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue = {
            owner: 'im-github-training'
            repo: 'im-github-training.github.io', // replace with the repository name
            title: 'Issue title', // replace with the issue title
            body: 'Issue body' // replace with the issue body
          };
          github.rest.issues.create(issue);
