name: Create Issue

on:
  workflow_dispatch:
  
permissions:
  issues: write
  contents: write

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create repository dispatch event
      uses: actions/github-script@v7
      with:
        script: |
          return await github.rest.repos.createDispatchEvent({
            owner: 'im-github-training',
            repo: 'im-github-training.github.io',
            event_type: 'my-event',
            client_payload: {
              key1: 'value1',
              key2: 'value2'
            }
          });
            
